apiVersion: apps/v1
kind: Deployment
metadata:
  name: diatom-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diatom-pub
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: diatom-pub
    spec:
      volumes:
        - name: client-cert
          secret:
            secretName: db-tls-secret
        - name: db-sql-volume
          # FIXME:
          emptyDir: {}

      initContainers:
        - name: flowdber
          image: flowlab/flowdber:0.3.6
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: db-sql-volume
              mountPath: /db
          envFrom:
            - configMapRef:
                name: diatom-pub-flowdber-config
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-pass-secret

      containers:
        - name: diatom-pub
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          envFrom:
            - configMapRef:
                name: diatom-pub-config
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-pass-secret
          volumeMounts:
            - mountPath: /etc/client-cert
              name: client-cert
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]