apiVersion: apps/v1
kind: Deployment
metadata:
  name: diatom-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diatom-pub
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: diatom-pub
    spec:
      containers:
        - name: diatom-pub
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              # TODO [grokrz]: This should be a /health endpoint
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              # TODO [grokrz]: This should be a /health endpoint
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          envFrom:
            - configMapRef:
                name: diatom-pub-config
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]