apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: diatom-pub
spec:
  targetRef:
    kind: Deployment
    name: diatom-pub
    apiVersion: apps/v1
  updatePolicy:
    updateMode: Auto