openapi: 3.0.3

info:
  title: "SRV API"
  version: 0.1.0
  description: Srv API.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: {{.SrvUrl}}
    description: API server

tags:
  - name: infra
    description: Service tag
  - name: authorization
    description: Author

paths:
    /health:
      get:
        tags:
          - infra
        summary: Healthcheck
        operationId: getHealth
        description: Healthcheck
        responses:
          200:
            description: OK
          429:
            $ref: '#/components/responses/TooManyRequests'

    /authors/{author_id}:
      get:
        tags:
          - author
        summary: Get author by id
        operationId: getAuthorById
        description: Get author by id
        parameters:
          - name: author_id
            in: path
            description: Author id
            required: true
            schema:
              type: string
              format: uuid
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Author'
          404:
            $ref: '#/components/responses/NotFound'
          429:
            $ref: '#/components/responses/TooManyRequests'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: The API Key
      in: header
      name: api-key
  schemas:
    Author:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Delia Owens
  responses:
    Unauthorized:
      description: API key is missing or invalid
    NotFound:
      description: Resource not found
    TooManyRequests:
      description: API has been called too many times in the last throttle period

security:
  - ApiKeyAuth: []